 CREATE TABLE record(
  ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TITLE TEXT,
  CONTENT TEXT,
  UPDATED_AT DATETIME,
  CREATED_AT DATETIME
);

CREATE TABLE tag( 
  ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TAG VARCHAR(64) UNIQUE
);

CREATE TABLE relation( 
  ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  ID_RECORD INTEGER NOT NULL,
  ID_TAG INTEGER NOT NULL,

  FOREIGN KEY (ID_RECORD) REFERENCES record(ID),
  FOREIGN KEY (ID_TAG) REFERENCES tag(ID)
)
